sudo: false
language: node_js

branches:
  only:
    - develop

services:
  - docker

script:
  - docker build -t apinf/platform:$DOCKER_TAG .
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push apinf/platform:$DOCKER_TAG
